<a href="https://colab.research.google.com/github/Veera9014/practice-data-science-code/blob/main/stats.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd

In [ ]:
sal = pd.read_csv('Salaries.csv')

In [ ]:
sal.head()

rank discipline  phd  service   sex  salary
0       Prof          B   56       49  Male  186960
1       Prof          A   20       20  Male  122400
2  AssocProf          A   20       17  Male   81285
3       Prof          B   23       23  Male  134778
4   AsstProf          B    1        0  Male   88000

In [ ]:
data = [
    [100,'Tom','Mgr',3000],
    [200,'Mary','Pgmr',4000],
    [300,'Pat','HR',2700],
    [400,'Pete','Pgmr',3700]
]

In [ ]:
edf = pd.DataFrame(  data,
                     columns=['eid','ename','role','salary'],
                     index=['e1','e2','e3','e4']
                  )

In [ ]:
edf

eid ename  role  salary
e1  100   Tom   Mgr    3000
e2  200  Mary  Pgmr    4000
e3  300   Pat    HR    2700
e4  400  Pete  Pgmr    3700

## Descriptive Statistics

#### Measures of Central Tendency

In [ ]:
# mean
sal['salary'].mean()

106278.56862745098

In [ ]:
edf['salary'].mean()

3350.0

In [ ]:
# Median
sal['salary'].median()

103994.0

In [ ]:
edf['salary'].median()

3350.0

In [ ]:
# Mode
sal['rank'].mode()

0    Prof
Name: rank, dtype: object

#### Measures of dispersion

In [ ]:
# Standard Deviation
edf['salary'].std()

602.7713773341708

In [ ]:
# Variance
edf['salary'].var()

363333.3333333333

In [ ]:
# Range
range_val = edf['salary'].max() - edf['salary'].min()
range_val

1300

In [ ]:
edf

eid ename  role  salary
e1  100   Tom   Mgr    3000
e2  200  Mary  Pgmr    4000
e3  300   Pat    HR    2700
e4  400  Pete  Pgmr    3700

#### Measures of Position

In [ ]:
# 10th Percentile / First Decile
edf['salary'].quantile(0.1)

2790.0

In [ ]:
sal['salary'].quantile(0.1)

73500.0

In [ ]:
# First Quartile
sal['salary'].quantile(0.25)

86500.0

In [ ]:
# 50th Percentile / Second Quartile / Median
edf['salary'].quantile(0.5)

3350.0

## Calculating probabilities

In [ ]:
from scipy import stats

In [ ]:
# Probability of x< 680
stats.norm.cdf(680, loc = 711, scale=29)

0.14254260383881612

In [ ]:
# Probability of x< 720
stats.norm.cdf(720, loc = 711, scale=29)c

0.621850627348053

In [ ]:
# Probability of x > 720
1 - stats.norm.cdf(720, loc = 711, scale=29)

0.37814937265194704

In [ ]:
# Probability of 680 < x< 720
stats.norm.cdf(720, loc = 711, scale=29) - stats.norm.cdf(680, loc = 711, scale=29)

0.47930802350923685

## Confidence Intervals

In [ ]:
from scipy import stats
import numpy as np

#### Population Stanadard deviation known

In [ ]:
confint = stats.norm.interval(0.95,loc=1990, scale = 2500/np.sqrt(140))
confint

(1575.8820248378292, 2404.1179751621708)

In [ ]:
np.round(confint)

array([1576., 2404.])

In [ ]:
confint = stats.norm.interval(0.90,loc=1990, scale = 2500/np.sqrt(140))
confint

(1642.4612396940827, 2337.538760305917)

In [ ]:
np.round(confint)

array([1642., 2338.])

#### Population Stanadard deviation NOT known

In [ ]:
confint = stats.t.interval(0.95,df=139,loc=1990, scale = 2833/np.sqrt(140))
confint

(1516.5999869168315, 2463.4000130831682)

In [ ]:
np.round(confint)

array([1517., 2463.])

### Find Z corresponding to C

In [ ]:
stats.norm.ppf(0.025)

-1.9599639845400545

In [ ]:
stats.norm.ppf(0.10)

-1.2815515655446004

In [ ]:
stats.norm.ppf(0.005)

-2.575829303548901

### Find t corresponding to C and df

In [ ]:
stats.t.ppf(0.025, df=139)

-1.9771777244761224